name: D8-feedback
favicon: null
layout_spectrum: 0.9128493831958622
typography_spectrum: 0.5873139116447419
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4647055340465158
  lightness: 0.5432350186165422
  saturation: 0.5313756975810975
  rhythmicContrast: 0.7878784439526498
purpose: []
