name: D8-feedback
favicon: null
layout_spectrum: 0
typography_spectrum: 0.85687
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b10f1a'
    - '#c1c1c1'
    - '#717171'
    - '#141414'
  brandStrength: 0.375
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
