layout_spectrum: 0.9165642040316015
typography_spectrum: 0.5544096424710006
color:
  brandColors:
    - '#C1000B'
    - '#A5A6A7'
    - '#000000'
    - '#333333'
    - '#808080'
  brandStrength: 0.04057630733586848
  lightness: 0.6858892894815654
  saturation: 0.47386253741569817
  rhythmicContrast: 0.91505222232081
name: "de-escalate.com\_"
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/31e13754-c9c2-43f8-8324-e1f5a444d4f0.png
content_rating:
  adult: false
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b5679543-0482-456b-ba60-052841508c46.png
navigation:
  - name: de-escalation.training
    url: 'http://de-escalation.training/'
    type: external
  - name: about
    url: 'http://de-escalate.com'
    type: external
  - name: FB
    url: 'http://facebook.com/descal8'
    type: external
title: de-escalation.training
description: participant views
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
