typography_spectrum: 0.49529
color:
  brandColors:
    - '#ffffff'
    - '#b10f1a'
    - '#c1c1c1'
    - '#717171'
    - '#141414'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.37665
analytics:
  google: null
  facebook: null
  twitter: null
name: de-escalate.com participants feedback
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: D8-Training
    url: 'http://de-escalation.training/'
    type: external
favicon: null
title: de-escalation
description: participant views
purpose: []
